# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Julia Ream
description: >- # this means to ignore newlines until "baseurl:"
  Hybrid methods for multiphysics flows
baseurl: "" # the subpath of the site
url: "https://juliaaream.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Research
    - name: Teaching
    - name: <a href="\REAM_CV.pdf">CV<\a>
    - name: Other

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: jream@math.fsu.edu
      link: mailto:jream@math.fsu.edu
#     - name: WeChat
#       value: YourWeChatUsername
#       link: "#"
  follow:
#     - name: Twitter
#       link: http://twitter.com/YourTwitterUsername
#       username: "@YourTwitterUsername"
#     - name: Facebook
#       link: http://facebook.com/YourFacebookUsername
    - name: LinkedIn
      link: https://www.linkedin.com/in/julia-ream-1b7998169/
    - name: GitHub
      link: http://github.com/juliaaream
#     - name: Dribbble
#       link: https://dribbble.com/YourDribbbleUsername
#     - name: RSS
#       link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
